apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: dev
  labels:
    app: busybox
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "echo 'Test' && sleep 600"]
  restartPolicy: Never