apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: dev
  labels:
    app: server
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    restartPolicy: Never
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
    resources:
      requests:
        cpu: "100m"
        memory: "100Mi"
      limits:
        cpu: "100m"
        memory: "100Mi"
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
  volumes:
  - name: html
    emptyDir: {}