apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  annotations:
    author: koray
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1  
  template:
    metadata:
      labels:
        app: nginx
    spec:
      terminationGracePeriodSeconds: 20
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 3        
        resources:
          # having requests and limits matched graduates the QoS of the pod to Guaranteed
          requests:
            cpu: "200m"
            memory: "200Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"          